r_encoding <- "UTF-8"
r_path <- '.'

library(ggplot2)
library(ggplotify)
library(shiny)
library(shinydashboard)
library(Seurat)
library(monocle)
library(rhandsontable)
library(circlize)
library(reshape2)
library(RColorBrewer)
library(pheatmap)
library(plyr)
library(dplyr)
library(zoo)
library(vegan)
library(UpSetR)
library(shinyWidgets)
# library('kohonen')
# library("viridis") 
# library('switchde')
options(shiny.maxRequestSize = 500*1024^2) 